/********************************************************************
 *        _       _         _
 *  _ __ | |_  _ | |  __ _ | |__   ___
 * | '__|| __|(_)| | / _` || '_ \ / __|
 * | |   | |_  _ | || (_| || |_) |\__ \
 * |_|    \__|(_)|_| \__,_||_.__/ |___/
 *
 * http://www.rt-labs.com
 * Copyright 2022 rt-labs AB, Sweden.
 * See LICENSE file in the project root for full license information.
 ********************************************************************/

/*
 * Generated by erpcgen 1.9.1 on Mon Sep  9 16:24:39 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */

#if !defined(_erpc_crc16_h_)
#define _erpc_crc16_h_

#if !defined(ERPC_GENERATED_CRC)
#define ERPC_GENERATED_CRC 50905
#else
#error "Macro 'ERPC_GENERATED_CRC' shouldn't be defined at this moment."
#endif

#endif // _erpc_crc16_h_
