/******************************************************************************
 * File Name:   retarget_io.c
 *
 * Description: This is the source code for the XMC MCU: UART Shell Example
 *              for ModusToolbox. This file implements the linking to the
 *              printf standard library functions.
 *
 * Related Document: See README.md
 *
 ******************************************************************************
 *
 * Copyright (c) 2015-2024, Infineon Technologies AG
 * All rights reserved.
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *****************************************************************************/

#include "cybsp.h"
#include "cy_utils.h"
#include "cy_retarget_io.h"
#include "retarget_io.h"
#include "cyhal_uart.h"

/*******************************************************************************/
/* Macros*/
#define ENABLE_EVENT                      1
#define FIFO_LEVEL                        0
#define DEBUG_UART_RX_FIFO_EVENT_PRIORITY 63

#define RX_BUF_SZ                         64

static uint8_t uart_rx_buf[RX_BUF_SZ];

/* Global Variables
*******************************************************************************/
RING_BUFFER_DEF (serial_buffer, SERIAL_BUFFER_SIZE);

cyhal_uart_event_callback_t UART_Isr (void)
{
   // Receive characters from UART and push into ringbuffer
   size_t len = RX_BUF_SZ;
   if (
      CY_RSLT_SUCCESS ==
         cyhal_uart_read (&cy_retarget_io_uart_obj, &uart_rx_buf, &len) &&
      len > 0)
   {
      uint8_t * data_ptr = uart_rx_buf;
      while (len--)
      {
         ring_buffer_put (&serial_buffer, *data_ptr++);
      }
   }
   return 0;
}


/*******************************************************************************
 * Function Name: retarget_io_init
 ********************************************************************************
 * Summary:
 * Initialize printf retarget
 *
 * Parameters:
 *  void
 *
 * Return:
 *  void
 *
 *******************************************************************************/
void retarget_io_init (void)
{
   serial_buffer.head = 0;
   serial_buffer.tail = 0;
   /* Enable RX_FIFO event and define the callback function when the vent occurs
    */
   cyhal_uart_register_callback (
      &cy_retarget_io_uart_obj,
      (cyhal_uart_event_callback_t)UART_Isr,
      NULL);
   cyhal_uart_enable_event (
      &cy_retarget_io_uart_obj,
      CYHAL_UART_IRQ_RX_FIFO,
      DEBUG_UART_RX_FIFO_EVENT_PRIORITY,
      ENABLE_EVENT);
   Cy_SCB_SetRxFifoLevel (cy_retarget_io_uart_obj.base, FIFO_LEVEL);
}

/*******************************************************************************
 * Function Name: _close
 ********************************************************************************
 * Summary:
 * Dummy implementation of std-library call to satisfy linking
 *
 * Parameters:
 *  int fd: file descriptor
 *
 * Return:
 *  int: -1 to indicate error
 *
 *******************************************************************************/
int _close (int fd)
{
   CY_UNUSED_PARAMETER (fd);
   return -1;
}

/*******************************************************************************
 * Function Name: _fstat
 ********************************************************************************
 * Summary:
 * Dummy implementation of std-library call to satisfy linking
 *
 * Parameters:
 *  int fd: file descriptor
 *  void *buffer: buffer pointer
 *
 * Return:
 *  int: -1 to indicate error
 *
 *******************************************************************************/
int _fstat (int fd, void * buffer)
{
   CY_UNUSED_PARAMETER (fd);
   CY_UNUSED_PARAMETER (buffer);
   return -1;
}

/*******************************************************************************
 * Function Name: _isatty
 ********************************************************************************
 * Summary:
 * Dummy implementation of std-library call to satisfy linking
 *
 * Parameters:
 *  int fd: file descriptor
 *
 * Return:
 *  int: 0 to indicate error
 *
 *******************************************************************************/
int _isatty (int fd)
{
   CY_UNUSED_PARAMETER (fd);
   return 0;
}

/*******************************************************************************
 * Function Name: _lseek
 ********************************************************************************
 * Summary:
 * Dummy implementation of std-library call to satisfy linking
 *
 * Parameters:
 *  int fd: file descriptor
 *  long offset: offset
 *  int origin: origin
 *
 * Return:
 *  int: -1 to indicate error
 *
 *******************************************************************************/
long _lseek (int fd, long offset, int origin)
{
   CY_UNUSED_PARAMETER (fd);
   CY_UNUSED_PARAMETER (offset);
   CY_UNUSED_PARAMETER (origin);
   return -1;
}

/*******************************************************************************
 * Function Name: _write
 ********************************************************************************
 * Summary:
 * Functional implementation of std-library to map output to UART
 *
 * Parameters:
 *  int fd: file descriptor
 *  const void *buf: pointer to buffer
 *  size_t count: buffer size
 *
 * Return:
 *  count of written characters
 *
 *******************************************************************************/
int _write (int fd, const void * buf, size_t count)
{
   CY_UNUSED_PARAMETER (fd);

   for (size_t i = 0; i < count; ++i)
   {
      /* Transmit single characters using UART */
      cyhal_uart_putc (&cy_retarget_io_uart_obj, *(const uint8_t *)buf);
      buf++;
   }
   return count;
}

/*******************************************************************************
 * Function Name: _read
 ********************************************************************************
 * Summary:
 * Functional implementation of std-library to map input to UART
 *
 * Parameters:
 *  int fd: file descriptor
 *  const void *buf: pointer to buffer
 *  size_t count: buffer size
 *
 * Return:
 *  count of read characters
 *
 *******************************************************************************/
int _read (int fd, const void * buf, size_t count)
{
   CY_UNUSED_PARAMETER (fd);
   int char_cnt = 0;

   for (size_t i = 0; i < count; ++i)
   {
      /* Pop single characters from ringbuffer, until ringbuffer is empty. */
      if (ring_buffer_get (&serial_buffer, (uint8_t *)buf) == RING_BUFFER_EMPTY_ERROR)
      {
         break;
      }

      char_cnt++;

      /* Stop reading if CR (Ox0D) character is received */
      /* New line character (CR) received ? */
      if (*(uint8_t *)buf == 0x0DU)
      {
         /* Yes, convert LF to '\n' char. */
         *(uint8_t *)buf = '\n';
         /* Stop loop and return received char(s) */
         break;
      }

      buf++;
   }

   return char_cnt;
}

/* [] END OF FILE */
