/******************************************************************************
 * File Name:   shell.c
 *
 * Description: This is the source code for the XMC MCU: UART Shell Example
 *              for ModusToolbox. Code derived from fNET Shell
 *              (https://github.com/butok/FNET/)
 *
 * Related Document: See README.md
 *
 ******************************************************************************
 *
 * Copyright (c) 2015-2024, Infineon Technologies AG
 * All rights reserved.
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *****************************************************************************/

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdarg.h>
#include "shell.h"
#include "retarget_io.h"
#include "ring_buffer.h"
#include "cyhal.h"
#include "cybsp.h"
#include "cy_retarget_io.h"
#include "retarget_io.h"
#include <FreeRTOS.h>
#include <task.h>

#include "osal.h"
#include "rte_shell.h"

/*******************************************************************************
 * Typedefs
 *******************************************************************************/
/* States of shell state machine */
typedef enum SHELL_STATE
{
   SHELL_STATE_INIT,           /* The Shell service is initialized to process
                                  next user command. */
   SHELL_STATE_GET_USER_INPUT, /* The Shell service is accepting user commands.
                                */
   SHELL_STATE_EXEC_CMD, /* The Shell service is executing user commands. */
   SHELL_STATE_END_CMD   /* The Shell service finished command execution. */
} SHELL_STATE_t;

/*******************************************************************************
 * Variables
 *******************************************************************************/

static SHELL_STATE_t shell_state;
static uint32_t shell_cmdline_pos;
static char shell_cmdline[SHELL_CMDLINE_SIZE];
static uint32_t shell_cmdline_prev_pos;
static char shell_cmdprev[SHELL_CMDLINE_SIZE];

/*
 * defined in linker script file uphy-linker-script.ld and used to
 * assemble all console commands defined in code using SHELL_CMD()
 * */
extern uint32_t cmds_start;
extern uint32_t cmds_end;

static TaskHandle_t console_task_hdl;

/*******************************************************************************
 * Macros
 *******************************************************************************/
/* Parameters of shell behaviour */
#define SHELL_ERR_SYNTAX ("Error: Invalid syntax for: %s")
#define SHELL_ERR_CMD    ("Error: No such command: %s")
#define SHELL_BACKSPACE  ((char)(0x08)) /* Backspace. */
#define SHELL_DELETE     ((char)(0x7F)) /* Delete. */
#define SHELL_CTRLC      ((char)(0x03)) /* Ctrl + C. */
#define SHELL_CR         ((char)(0x0D)) /* CR. */
#define SHELL_LF         ((char)(0x0A)) /* LF. */
#define SHELL_ESC        ((char)(0x1B)) /* Esc. */
#define SHELL_SPACE      ((char)(0x20)) /* Space. */

/* we entered handle_esc() when one character was available
 * ensure we don't attempt to read additional data from stdin
 * before new data is available in serial buffer */
static char wait_esc_data (void)
{
   while (ring_buffer_avail (&serial_buffer) == 0)
      vTaskDelay (1);
   return getchar();
}

void handle_esc (void)
{
   char c;

   c = wait_esc_data(); // Read the next character (usually '[')
   if (c == '[')
   {
      c = wait_esc_data(); // Read the next character to determine the key
      switch (c)
      {
      case 'A':

         /* arrow up, repeat previous command */
         memcpy (shell_cmdline, shell_cmdprev, SHELL_CMDLINE_SIZE);
         shell_cmdline_pos = shell_cmdline_prev_pos;

         /* clear line and rewrite command */
         printf ("\r\033[K%s%s", SHELL_PROMPT, shell_cmdline);
         fflush (stdout);
         break;
      case 'B':
         /* arrow down */
         break;
      case 'C':
         /* arrow right */
         break;
      case 'D':
         /* arrow left */
         break;
      default:
         printf ("Unknown escape sequence detected! [%x]\n", c);
         break;
      }
   }
}

/*******************************************************************************
 * Function Name: shell_println
 ********************************************************************************
 * Summary:
 * Wrapping of printf for formatted output including linefeed.
 *
 * Parameters:
 *  const char *format: format string
 *  ...: flexible parameter list for formatted output
 *
 *
 * Return:
 *  int32_t: number of characters printed
 *
 *******************************************************************************/
int32_t shell_println (const char * format, ...)
{
   int32_t result;
   va_list ap;

   va_start (ap, format);
   result = vprintf (format, ap);
   /* Add new line.*/
   result += printf ("\r\n");
   va_end (ap);

   return result;
}

/*******************************************************************************
 * Function Name: shell_state_machine
 ********************************************************************************
 * Summary:
 * Implementation of the shell internal state-machine.
 * see https://github.com/butok/FNET/ for implementation details
 *
 * Parameters:
 *  void
 *
 * Return:
 *  void
 *
 *******************************************************************************/
void shell_state_machine (void)
{
   int32_t ch;

   switch (shell_state)
   {
   case SHELL_STATE_INIT:
      printf ("%s", SHELL_PROMPT);
      shell_state = SHELL_STATE_GET_USER_INPUT;
      break;

   case SHELL_STATE_GET_USER_INPUT:
      if (ring_buffer_avail (&serial_buffer) > 0)
      {
         ch = getchar();
         if (ch != EOF)
         {
            /* Check if
             * 1. enter was pressed or
             * 2. shell_cmdline buffer has only 1 character left, reserved for
             * zero termination
             */
            if (((char)ch != SHELL_LF) && (shell_cmdline_pos < (SHELL_CMDLINE_SIZE - 1)))
            {
               switch (ch)
               {
               case SHELL_ESC:
                  handle_esc();
                  break;
               case SHELL_BACKSPACE:
               case SHELL_DELETE:
                  if (shell_cmdline_pos > 0U)
                  {
                     shell_cmdline_pos -= 1U;
                     putchar (SHELL_BACKSPACE);
                     putchar (' ');
                     putchar (SHELL_BACKSPACE);
                  }
                  break;

               default:
                  if ((shell_cmdline_pos + 1U) < SHELL_CMDLINE_SIZE)
                  {
                     /* Only printable characters. */
                     if (((char)ch >= SHELL_SPACE) && ((char)ch <= SHELL_DELETE))
                     {
                        shell_cmdline[shell_cmdline_pos] = (char)ch;
                        shell_cmdline_pos++;
                        putchar ((char)ch);
                     }
                  }
                  break;
               }
            }
            else
            {
               /* Append zero termination to command and start execution */
               shell_cmdline[shell_cmdline_pos] = '\0';

               putchar (SHELL_CR);
               putchar (SHELL_LF);

               shell_state = SHELL_STATE_EXEC_CMD;
            }
         }
      }
      break;

   case SHELL_STATE_EXEC_CMD:

      /* store copy of command line before chopped up into separate arguments */
      if (strlen (shell_cmdline) > 0)
      {
         memcpy (shell_cmdprev, shell_cmdline, SHELL_CMDLINE_SIZE);
         shell_cmdline_prev_pos = strlen (shell_cmdprev);
      }

      rte_shell_execute(shell_cmdline);

      shell_state = SHELL_STATE_END_CMD;
      break;

   case SHELL_STATE_END_CMD:
      shell_state = SHELL_STATE_INIT;
      shell_cmdline_pos = 0u;
      shell_cmdline[0] = 0u;
      break;

   default:
      break;
   }
}

/*******************************************************************************
 * Function Name: shell_init
 ********************************************************************************
 * Summary:
 * Initialize printf retarget
 *
 * Parameters:
 *  const shell_cmd_t_t *const cmd_table: Table to specify shell commands
 *  void (*init)(void): function ptr which is called at the end of
 *initialization e.g. to parse a welcome string to the terminal
 *
 * Return:
 *  void
 *
 *******************************************************************************/


/*******************************************************************************
 * Function Name: my_shell_init
 ********************************************************************************
 * Summary:
 * Welcome screen shown when shell is initialized
 * Override this function to customize the welcome screen. This is done by
 * defining a function with the same name in the application code without the
 * weak attribute.
 *
 * Parameters:
 *  void
 *
 * Return:
 *  void
 *
 *******************************************************************************/
__attribute__ ((weak)) void shell_print_start_banner (void)
{
   const char DELIMITER_STR[] =
      "************************************************";

   /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
   printf ("\x1b[2J\x1b[;H");

   shell_println ("\r\n%s", DELIMITER_STR);
   shell_println (" %s", "Shell Application");
   shell_println (DELIMITER_STR);
   shell_println (" Version %s", "1.0.0");
   shell_println (" Built %s", __DATE__ " at " __TIME__);

   shell_println ("\n Enter 'help' for command list.");
   shell_println ("%s\n", DELIMITER_STR);
}

static void my_shell_init (void)
{
   shell_print_start_banner();
}

static void shell_init (void (*init) (void))
{
   rte_shell_init("");

   setvbuf (stdout, NULL, _IONBF, 0);

   shell_state = SHELL_STATE_INIT;
   shell_cmdline_pos = 0u;
   shell_cmdline[0] = 0u;

   init();
}

static void console_task (void *)
{
   while (true)
   {
      shell_state_machine();
      vTaskDelay (1);
   }
}

void shell_console_init (void)
{
   cy_rslt_t result;

   /* Initialize retarget-io to use the debug UART port */
   /* Please note that _read() and _write() functions are re-defined in
    * retarget_io.c */

   result = cy_retarget_io_init_fc (
      CYBSP_DEBUG_UART_TX,
      CYBSP_DEBUG_UART_RX,
      NC,
      NC,
      CY_RETARGET_IO_BAUDRATE);

   CY_ASSERT (result == CY_RSLT_SUCCESS);

   retarget_io_init();

   /* initialize shell console */
   shell_init (my_shell_init);

   xTaskCreate (
      console_task,
      "shell_console",
      4000,
      (void *)NULL,
      OS_PRIORITY_NORMAL,
      &console_task_hdl);
}
